# Generated by Django 3.2 on 2021-06-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
